### PR TITLE
Remove .npmignore / Update devDependencies

### PR DESCRIPTION
**Pull request by shinnn**
- I removed unnecessary .npmignore. package.json already has `files` field.
- I updated [fill-range](https://www.npmjs.com/package/fill-range) to v2.1.0.

### CODE REVIEW

**Comment by shinnn** [comment]
@jonschlinkert How about publishing v1.0.0?

**Comment by shinnn** [comment]
Hmm, no build status. The test passes on my machine though.

**Comment by jonschlinkert** [comment]
thanks! added you as a collab too

**Comment by jonschlinkert** [comment]
forgot about the 1.0 thing. I'll do that and add you to npm too

**Comment by jonschlinkert** [comment]
done

**Comment by shinnn** [comment]
Great! Thanks :)

**Comment by jonschlinkert** [comment]
thank you too!

**Pull request merged**
